import {whatsappConfig,sendInvitation} from '../../../lib/whatsapp';
import {db,identity,isAdmin,json,sameOrigin,str,bucket,readBounded,requestReference} from '../../../lib/momo-server';
export async function GET(req:Request){try{const user=await identity(),admin=isAdmin(user),q=new URL(req.url).searchParams.get('view')||'home';
if(q==='home')return json({events:(await db().prepare('SELECT * FROM events ORDER BY date ASC LIMIT 30').all()).results,gallery:(await db().prepare('SELECT * FROM gallery ORDER BY created DESC LIMIT 60').all()).results});
if(!user)return json({error:'Sign in to join the Momo community.',signedIn:false},401);
if(q==='me'){const invite=await db().prepare('SELECT i.*,e.title AS eventTitle FROM invites i LEFT JOIN events e ON i.event_id=e.id WHERE i.user_id=?').bind(user.userId).first<any>();const delivery=invite?await db().prepare('SELECT status FROM deliveries WHERE user_id=? ORDER BY created DESC LIMIT 1').bind(user.userId).first<any>():null;return json({signedIn:true,admin,profile:await db().prepare('SELECT nickname,avatar,photo FROM profiles WHERE id=?').bind(user.userId).first(),invite:invite?{city:invite.city,status:invite.status,event_id:invite.event_id,eventTitle:invite.eventTitle,created:invite.created,foodTheme:invite.food_theme,maskedPhone:'•••• '+invite.phone.slice(-4),reference:await requestReference(user.userId,invite.created),deliveryStatus:delivery?.status||'Not sent'}:null})}
if(q==='chat'){const room=new URL(req.url).searchParams.get('room')||'weekend';if(!['weekend','food','games'].includes(room))return json({error:'Unknown room.'},400);return json({messages:(await db().prepare('SELECT m.id,m.body,m.created,p.nickname,p.avatar,p.photo,(m.user_id=?) AS mine FROM messages m JOIN profiles p ON m.user_id=p.id WHERE m.room=? AND NOT EXISTS (SELECT 1 FROM blocks b WHERE b.user_id=? AND b.blocked_id=m.user_id) ORDER BY m.created DESC LIMIT 80').bind(user.userId,room,user.userId).all()).results.reverse()})}
if(q==='host'){if(!admin)return json({error:'Host access is restricted. The owner must configure the host email allowlist before using this page.'},403);return json({whatsapp:whatsappConfig(),deliveries:(await db().prepare('SELECT * FROM deliveries ORDER BY created DESC LIMIT 200').all()).results,invites:(await db().prepare('SELECT i.*,p.nickname FROM invites i LEFT JOIN profiles p ON i.user_id=p.id ORDER BY i.created DESC LIMIT 200').all()).results,reports:(await db().prepare('SELECT r.*,m.body FROM reports r LEFT JOIN messages m ON r.message_id=m.id ORDER BY r.created DESC LIMIT 100').all()).results})}return json({error:'Not found'},404)
}catch(e){console.error('momo read failed');return json({error:'We could not load this right now. Please try again.'},503)}}
export async function POST(req:Request){try{if(!sameOrigin(req))return json({error:'Please submit from this site.'},403);const user=await identity();if(!user)return json({error:'Sign in to continue.'},401);if(Number(req.headers.get('content-length')||0)>10000)return json({error:'Request too large.'},413);const raw=new TextDecoder().decode(await readBounded(req,10000));if(raw.length>10000)return json({error:'Request too large.'},413);const b=JSON.parse(raw),now=Date.now(),id=crypto.randomUUID();
if(b.action==='profile'){if(b.adult!==true||b.rules!==true)return json({error:'Please confirm you are 18+ and accept the community rules.'},400);const nick=str(b.nickname,2,30);if(!Number.isInteger(b.avatar)||b.avatar<0||b.avatar>5)return json({error:'Choose a food avatar.'},400);await db().prepare('INSERT INTO profiles(id,nickname,avatar,created) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET nickname=excluded.nickname,avatar=excluded.avatar').bind(user.userId,nick,b.avatar,now).run();return json({ok:true})}
if(b.action==='invite'){const phone=str(b.phone,8,20).replace(/[\s()-]/g,'');if(!/^\+[1-9]\d{7,14}$/.test(phone)||b.consent!==true||b.adult!==true)return json({error:'Use an international phone number and confirm both checkboxes.'},400);const city=str(b.city,2,60);if(b.eventId&&!(await db().prepare('SELECT id FROM events WHERE id=?').bind(b.eventId).first()))return json({error:'This meetup is no longer available.'},400);await db().prepare("INSERT INTO invites(user_id,phone,city,event_id,consent,status,created,food_theme) VALUES(?,?,?,?,?,'requested',?,?) ON CONFLICT(user_id) DO UPDATE SET phone=excluded.phone,city=excluded.city,event_id=excluded.event_id,consent=excluded.consent,status='requested',created=invites.created,food_theme=excluded.food_theme").bind(user.userId,phone,city,b.eventId||null,'whatsapp-weekend-invites-v2:2026-10-05',now,b.foodTheme==='menu'?'menu':'momo').run();return json({ok:true})}
if(b.action==='withdraw'){await db().batch([db().prepare("UPDATE deliveries SET status='withdrawn',updated=? WHERE user_id=?").bind(now,user.userId),db().prepare('DELETE FROM invites WHERE user_id=?').bind(user.userId)]);return json({ok:true})}
if(b.action==='message'){if(!['weekend','food','games'].includes(b.room))return json({error:'Choose a room.'},400);const body=str(b.body,1,500);const throttle=await db().prepare('UPDATE profiles SET last_message=? WHERE id=? AND last_message<?').bind(now,user.userId,now-3000).run();if(!throttle.meta.changes)return json({error:'Create your profile first, or wait a few seconds before sending again.'},429);await db().prepare('INSERT INTO messages(id,user_id,room,body,created) VALUES(?,?,?,?,?)').bind(id,user.userId,b.room,body,now).run();return json({ok:true})}
if(b.action==='report'||b.action==='block'){const message=await db().prepare('SELECT user_id FROM messages WHERE id=?').bind(str(b.messageId,1,60)).first<{user_id:string}>();if(!message)return json({error:'Message not found.'},404);if(b.action==='report')await db().prepare('INSERT INTO reports(id,user_id,message_id,reason,created) VALUES(?,?,?,?,?)').bind(id,user.userId,b.messageId,str(b.reason,3,300),now).run();else await db().prepare('INSERT OR IGNORE INTO blocks(id,user_id,blocked_id) VALUES(?,?,?)').bind(user.userId+':'+message.user_id,user.userId,message.user_id).run();return json({ok:true})}
if(b.action==='deleteAccount'){await db().prepare('DELETE FROM deliveries WHERE user_id=?').bind(user.userId).run();const p=await db().prepare('SELECT photo FROM profiles WHERE id=?').bind(user.userId).first<{photo:string}>();if(p?.photo)await bucket().delete(p.photo);await db().batch([db().prepare('DELETE FROM reports WHERE user_id=? OR message_id IN (SELECT id FROM messages WHERE user_id=?)').bind(user.userId,user.userId),db().prepare('DELETE FROM messages WHERE user_id=?').bind(user.userId),db().prepare('DELETE FROM invites WHERE user_id=?').bind(user.userId),db().prepare('DELETE FROM blocks WHERE user_id=? OR blocked_id=?').bind(user.userId,user.userId),db().prepare('DELETE FROM profiles WHERE id=?').bind(user.userId)]);return json({ok:true})}
if(!isAdmin(user))return json({error:'Host access required.'},403);
if(b.action==='sendWhatsApp')return json(await sendInvitation(str(b.userId,1,150),str(b.eventId,1,60)));
if(b.action==='requestStatus'){if(!['requested','reviewed','confirmed','declined'].includes(b.status))return json({error:'Unknown request status'},400);await db().prepare('UPDATE invites SET status=? WHERE user_id=?').bind(b.status,str(b.userId,1,150)).run();return json({ok:true})}
if(b.action==='event'){const date=str(b.date,10,35);if(!Number.isFinite(Date.parse(date)))return json({error:'Choose a valid date.'},400);await db().prepare('INSERT INTO events(id,title,date,venue,cost,description,category,created) VALUES(?,?,?,?,?,?,?,?)').bind(id,str(b.title,3,100),date,str(b.venue,3,150),str(b.cost,1,100),str(b.description,5,1000),str(b.category,2,30),now).run();return json({ok:true})}
if(b.action==='removeEvent'){await db().prepare('DELETE FROM events WHERE id=?').bind(str(b.id,1,60)).run();return json({ok:true})}
if(b.action==='removeMessage'){await db().batch([db().prepare('DELETE FROM reports WHERE message_id=?').bind(str(b.id,1,60)),db().prepare('DELETE FROM messages WHERE id=?').bind(b.id)]);return json({ok:true})}
if(b.action==='removePhoto'){await bucket().delete(str(b.id,1,100));await db().prepare('DELETE FROM gallery WHERE id=?').bind(b.id).run();return json({ok:true})}
if(b.action==='resolveReport'){await db().prepare('DELETE FROM reports WHERE id=?').bind(str(b.id,1,60)).run();return json({ok:true})}
return json({error:'Unknown action.'},400)
}catch(e){return json({error:e instanceof Error&&e.message.startsWith('Please')?e.message:'We could not save that. Please try again.'},400)}}
