import {env} from 'cloudflare:workers';
import {whatsappConfig,sendInvitation} from '../../../lib/whatsapp';
import {db,identity,isAdmin,json,sameOrigin,str,bucket,readBounded,requestReference,platform,photosEnabled} from '../../../lib/momo-server';
const ROOMS=['weekend','food','games'];
const LETTERS=['hero','princess','notebook'];
const WISH_DAYS=45*86400000;
const authMode=()=>platform()==='vercel'?'device':'chatgpt';
const storage=()=>(env as any).MOMO_STORAGE||'durable';
async function wishBoard(user:any){
  const since=Date.now()-WISH_DAYS;
  const rows=(await db().prepare('SELECT w.id,w.user_id,w.title,w.when_text,w.area,w.spots,w.status,w.created,p.nickname,p.avatar,(SELECT COUNT(*) FROM wish_joins j WHERE j.wish_id=w.id) AS joined,(SELECT e.id FROM events e WHERE e.wish_id=w.id ORDER BY e.created DESC LIMIT 1) AS event_id FROM wishes w LEFT JOIN profiles p ON p.id=w.user_id WHERE w.created>? ORDER BY w.created DESC LIMIT 40').bind(since).all<any>()).results;
  const gangs:Record<string,{nickname:string,avatar:number}[]>={};const mine=new Set<string>();
  if(user){
    for(const g of (await db().prepare('SELECT j.wish_id,j.user_id,p.nickname,p.avatar FROM wish_joins j JOIN wishes w ON w.id=j.wish_id LEFT JOIN profiles p ON p.id=j.user_id WHERE w.created>? ORDER BY j.created ASC').bind(since).all<any>()).results){(gangs[g.wish_id]??=[]).push({nickname:g.nickname||'someone',avatar:Number(g.avatar)||0});if(g.user_id===user.userId)mine.add(g.wish_id)}
  }
  // Members see nicknames; signed-out visitors only see the wish and the head count.
  return rows.map(w=>({id:w.id,title:w.title,whenText:w.when_text,area:w.area,spots:Number(w.spots),status:w.event_id?'planned':w.status,eventId:w.event_id||null,created:Number(w.created),joined:Number(w.joined),mine:!!user&&w.user_id===user.userId,joinedByMe:mine.has(w.id),by:user?{nickname:w.nickname||'someone',avatar:Number(w.avatar)||0}:null,gang:user?gangs[w.id]||[]:[]}));
}
export async function GET(req:Request){try{const user=await identity(),admin=isAdmin(user),q=new URL(req.url).searchParams.get('view')||'home';
if(q==='home')return json({events:(await db().prepare('SELECT * FROM events ORDER BY date ASC LIMIT 30').all()).results,gallery:(await db().prepare('SELECT * FROM gallery ORDER BY created DESC LIMIT 60').all()).results,wishes:await wishBoard(user)});
if(!user)return json({error:'Pull up a chair to join the Momo community.',signedIn:false,auth:authMode(),storage:storage()},401);
if(q==='me'){const invite=await db().prepare('SELECT i.*,e.title AS eventTitle FROM invites i LEFT JOIN events e ON i.event_id=e.id WHERE i.user_id=?').bind(user.userId).first<any>();const delivery=invite?await db().prepare('SELECT status FROM deliveries WHERE user_id=? ORDER BY created DESC LIMIT 1').bind(user.userId).first<any>():null;return json({signedIn:true,admin,auth:authMode(),storage:storage(),photos:photosEnabled(),profile:await db().prepare('SELECT nickname,avatar,photo FROM profiles WHERE id=?').bind(user.userId).first(),invite:invite?{city:invite.city,status:invite.status,event_id:invite.event_id,eventTitle:invite.eventTitle,created:invite.created,foodTheme:invite.food_theme,letterStyle:invite.letter_style||'notebook',maskedPhone:'•••• '+invite.phone.slice(-4),reference:await requestReference(user.userId,invite.created),deliveryStatus:delivery?.status||'Not sent'}:null})}
if(q==='chat'){const room=new URL(req.url).searchParams.get('room')||'weekend';if(!ROOMS.includes(room))return json({error:'Unknown room.'},400);return json({messages:(await db().prepare('SELECT m.id,m.body,m.created,p.nickname,p.avatar,p.photo,(m.user_id=?) AS mine FROM messages m JOIN profiles p ON m.user_id=p.id WHERE m.room=? AND NOT EXISTS (SELECT 1 FROM blocks b WHERE b.user_id=? AND b.blocked_id=m.user_id) ORDER BY m.created DESC LIMIT 80').bind(user.userId,room,user.userId).all()).results.reverse()})}
if(q==='host'){if(!admin)return json({error:'Host access is restricted.',auth:authMode()},403);return json({whatsapp:whatsappConfig(),deliveries:(await db().prepare('SELECT * FROM deliveries ORDER BY created DESC LIMIT 200').all()).results,invites:(await db().prepare('SELECT i.*,p.nickname FROM invites i LEFT JOIN profiles p ON i.user_id=p.id ORDER BY i.created DESC LIMIT 200').all()).results,reports:(await db().prepare("SELECT r.*,CASE WHEN r.kind='wish' THEN 'Wish: '||w.title ELSE m.body END AS body FROM reports r LEFT JOIN messages m ON r.kind='message' AND r.message_id=m.id LEFT JOIN wishes w ON r.kind='wish' AND r.message_id=w.id ORDER BY r.created DESC LIMIT 100").all()).results})}return json({error:'Not found'},404)
}catch(e){console.error('momo read failed',e);return json({error:'We could not load this right now. Please try again.'},503)}}
export async function POST(req:Request){try{if(!sameOrigin(req))return json({error:'Please submit from this site.'},403);const user=await identity();if(!user)return json({error:'Pull up a chair first.'},401);if(Number(req.headers.get('content-length')||0)>10000)return json({error:'Request too large.'},413);const raw=new TextDecoder().decode(await readBounded(req,10000));if(raw.length>10000)return json({error:'Request too large.'},413);const b=JSON.parse(raw),now=Date.now(),id=crypto.randomUUID();
const profile=()=>db().prepare('SELECT nickname FROM profiles WHERE id=?').bind(user.userId).first();
if(b.action==='profile'){if(b.adult!==true||b.rules!==true)return json({error:'Please confirm you are 18+ and accept the community rules.'},400);const nick=str(b.nickname,2,30);if(!Number.isInteger(b.avatar)||b.avatar<0||b.avatar>5)return json({error:'Choose a food avatar.'},400);await db().prepare('INSERT INTO profiles(id,nickname,avatar,created) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET nickname=excluded.nickname,avatar=excluded.avatar').bind(user.userId,nick,b.avatar,now).run();return json({ok:true})}
if(b.action==='invite'){const phone=str(b.phone,8,20).replace(/[\s()-]/g,'');if(!/^\+[1-9]\d{7,14}$/.test(phone)||b.consent!==true||b.adult!==true)return json({error:'Use an international phone number (like +91…) and confirm both checkboxes.'},400);const city=str(b.city,2,60);const letter=LETTERS.includes(b.letterStyle)?b.letterStyle:'notebook';if(b.eventId&&!(await db().prepare('SELECT id FROM events WHERE id=?').bind(b.eventId).first()))return json({error:'This meetup is no longer available.'},400);await db().prepare("INSERT INTO invites(user_id,phone,city,event_id,consent,status,created,food_theme,letter_style) VALUES(?,?,?,?,?,'requested',?,?,?) ON CONFLICT(user_id) DO UPDATE SET phone=excluded.phone,city=excluded.city,event_id=excluded.event_id,consent=excluded.consent,status='requested',created=invites.created,food_theme=excluded.food_theme,letter_style=excluded.letter_style").bind(user.userId,phone,city,b.eventId||null,'whatsapp-weekend-invites-v2:2026-10-05',now,b.foodTheme==='menu'?'menu':'momo',letter).run();return json({ok:true})}
if(b.action==='withdraw'){await db().batch([db().prepare("UPDATE deliveries SET status='withdrawn',updated=? WHERE user_id=?").bind(now,user.userId),db().prepare('DELETE FROM invites WHERE user_id=?').bind(user.userId)]);return json({ok:true})}
if(b.action==='message'){if(!ROOMS.includes(b.room))return json({error:'Choose a room.'},400);const body=str(b.body,1,500);const throttle=await db().prepare('UPDATE profiles SET last_message=? WHERE id=? AND last_message<?').bind(now,user.userId,now-3000).run();if(!throttle.meta.changes)return json({error:'Create your nickname first, or wait a few seconds before sending again.'},429);await db().prepare('INSERT INTO messages(id,user_id,room,body,created) VALUES(?,?,?,?,?)').bind(id,user.userId,b.room,body,now).run();return json({ok:true})}
if(b.action==='report'||b.action==='block'){const message=await db().prepare('SELECT user_id FROM messages WHERE id=?').bind(str(b.messageId,1,60)).first<{user_id:string}>();if(!message)return json({error:'Message not found.'},404);if(b.action==='report')await db().prepare('INSERT INTO reports(id,user_id,message_id,reason,created) VALUES(?,?,?,?,?)').bind(id,user.userId,b.messageId,str(b.reason,3,300),now).run();else await db().prepare('INSERT OR IGNORE INTO blocks(id,user_id,blocked_id) VALUES(?,?,?)').bind(user.userId+':'+message.user_id,user.userId,message.user_id).run();return json({ok:true})}
if(b.action==='wish'){if(!await profile())return json({error:'Pick a nickname first, so your gang knows who made the wish.'},400);const title=str(b.title,3,80),whenText=str(b.whenText,2,60),area=str(b.area,2,60),spots=Number(b.spots);if(!Number.isInteger(spots)||spots<2||spots>12)return json({error:'A gang is 2 to 12 people.'},400);const recent=await db().prepare('SELECT COUNT(*) AS n FROM wishes WHERE user_id=? AND created>?').bind(user.userId,now-7*86400000).first<any>();if(Number(recent?.n)>=3)return json({error:'Three wishes a week. Let these come true first.'},429);await db().batch([db().prepare("INSERT INTO wishes(id,user_id,title,when_text,area,spots,status,created) VALUES(?,?,?,?,?,?,'open',?)").bind(id,user.userId,title,whenText,area,spots,now),db().prepare('INSERT INTO wish_joins(id,wish_id,user_id,created) VALUES(?,?,?,?)').bind(id+':'+user.userId,id,user.userId,now)]);return json({ok:true,id})}
if(b.action==='joinWish'||b.action==='leaveWish'||b.action==='removeWish'||b.action==='reportWish'){const wish=await db().prepare('SELECT id,user_id,spots,created FROM wishes WHERE id=?').bind(str(b.id,1,60)).first<any>();if(!wish||Number(wish.created)<now-WISH_DAYS)return json({error:'This wish is no longer on the wall.'},404);
  if(b.action==='reportWish'){if(wish.user_id===user.userId)return json({error:'You can remove your own wish instead.'},400);await db().prepare("INSERT INTO reports(id,user_id,message_id,kind,reason,created) VALUES(?,?,?,'wish',?,?)").bind(id,user.userId,wish.id,str(b.reason,3,300),now).run();return json({ok:true})}
  if(b.action==='removeWish'){if(wish.user_id!==user.userId&&!isAdmin(user))return json({error:'Only the person who made this wish can remove it.'},403);await db().batch([db().prepare("DELETE FROM reports WHERE kind='wish' AND message_id=?").bind(wish.id),db().prepare('DELETE FROM wish_joins WHERE wish_id=?').bind(wish.id),db().prepare('DELETE FROM wishes WHERE id=?').bind(wish.id)]);return json({ok:true})}
  if(wish.user_id===user.userId)return json({error:'You made this wish, so you’re already in the gang.'},400);
  if(b.action==='leaveWish'){await db().batch([db().prepare('DELETE FROM wish_joins WHERE wish_id=? AND user_id=?').bind(wish.id,user.userId),db().prepare("UPDATE wishes SET status='open' WHERE id=?").bind(wish.id)]);return json({ok:true})}
  if(!await profile())return json({error:'Pick a nickname first, so the gang knows who’s coming.'},400);
  const count=Number((await db().prepare('SELECT COUNT(*) AS n FROM wish_joins WHERE wish_id=?').bind(wish.id).first<any>())?.n||0);
  if(await db().prepare('SELECT id FROM wish_joins WHERE wish_id=? AND user_id=?').bind(wish.id,user.userId).first())return json({ok:true});
  if(count>=Number(wish.spots))return json({error:'This gang is full. Make a wish for the next one!'},409);
  await db().batch([db().prepare('INSERT OR IGNORE INTO wish_joins(id,wish_id,user_id,created) VALUES(?,?,?,?)').bind(wish.id+':'+user.userId,wish.id,user.userId,now),db().prepare("UPDATE wishes SET status=CASE WHEN (SELECT COUNT(*) FROM wish_joins WHERE wish_id=?)>=spots THEN 'ready' ELSE 'open' END WHERE id=?").bind(wish.id,wish.id)]);
  return json({ok:true})}
if(b.action==='deleteAccount'){await db().prepare('DELETE FROM deliveries WHERE user_id=?').bind(user.userId).run();const p=await db().prepare('SELECT photo FROM profiles WHERE id=?').bind(user.userId).first<{photo:string}>();if(p?.photo&&photosEnabled())await bucket().delete(p.photo);await db().batch([db().prepare('DELETE FROM reports WHERE user_id=? OR message_id IN (SELECT id FROM messages WHERE user_id=?) OR message_id IN (SELECT id FROM wishes WHERE user_id=?)').bind(user.userId,user.userId,user.userId),db().prepare('DELETE FROM messages WHERE user_id=?').bind(user.userId),db().prepare('DELETE FROM invites WHERE user_id=?').bind(user.userId),db().prepare('DELETE FROM blocks WHERE user_id=? OR blocked_id=?').bind(user.userId,user.userId),db().prepare('DELETE FROM wish_joins WHERE user_id=? OR wish_id IN (SELECT id FROM wishes WHERE user_id=?)').bind(user.userId,user.userId),db().prepare('DELETE FROM wishes WHERE user_id=?').bind(user.userId),db().prepare("UPDATE wishes SET status=CASE WHEN (SELECT COUNT(*) FROM wish_joins j WHERE j.wish_id=wishes.id)>=spots THEN 'ready' ELSE 'open' END"),db().prepare('DELETE FROM profiles WHERE id=?').bind(user.userId),db().prepare('DELETE FROM sessions WHERE user_id=?').bind(user.userId)]);return json({ok:true})}
if(!isAdmin(user))return json({error:'Host access required.'},403);
if(b.action==='sendWhatsApp')return json(await sendInvitation(str(b.userId,1,150),str(b.eventId,1,60)));
if(b.action==='requestStatus'){if(!['requested','reviewed','confirmed','declined'].includes(b.status))return json({error:'Unknown request status'},400);await db().prepare('UPDATE invites SET status=? WHERE user_id=?').bind(b.status,str(b.userId,1,150)).run();return json({ok:true})}
if(b.action==='event'){const date=str(b.date,10,35);if(!Number.isFinite(Date.parse(date)))return json({error:'Choose a valid date.'},400);const wishId=typeof b.wishId==='string'&&b.wishId?b.wishId:null;if(wishId&&!(await db().prepare('SELECT id FROM wishes WHERE id=?').bind(wishId).first()))return json({error:'That wish is no longer on the wall.'},400);await db().prepare('INSERT INTO events(id,title,date,venue,cost,description,category,wish_id,created) VALUES(?,?,?,?,?,?,?,?,?)').bind(id,str(b.title,3,100),date,str(b.venue,3,150),str(b.cost,1,100),str(b.description,5,1000),str(b.category,2,30),wishId,now).run();return json({ok:true})}
if(b.action==='removeEvent'){await db().prepare('DELETE FROM events WHERE id=?').bind(str(b.id,1,60)).run();return json({ok:true})}
if(b.action==='removeMessage'){await db().batch([db().prepare('DELETE FROM reports WHERE message_id=?').bind(str(b.id,1,60)),db().prepare('DELETE FROM messages WHERE id=?').bind(b.id)]);return json({ok:true})}
if(b.action==='removePhoto'){await bucket().delete(str(b.id,1,100));await db().prepare('DELETE FROM gallery WHERE id=?').bind(b.id).run();return json({ok:true})}
if(b.action==='resolveReport'){await db().prepare('DELETE FROM reports WHERE id=?').bind(str(b.id,1,60)).run();return json({ok:true})}
return json({error:'Unknown action.'},400)
}catch(e){return json({error:e instanceof Error&&e.message.startsWith('Please')?e.message:'We could not save that. Please try again.'},400)}}
