'use client';
import {useEffect,useState,FormEvent} from 'react';
import {X,ShieldCheck,MessageCircle,Lock,Send,Flag,Home,Armchair,LogOut,KeyRound} from 'lucide-react';
import PlayfulHome from './home-playful';
import {useBrand,themeNames,themeKinds,ThemeSwitch,wordmark,FoodIcon,Cast} from './brand';
import HostDesk from './host-desk';
import {Avatar} from './wishes';
import {Letters,BadgeMaker} from './letters';
import {LETTER_STYLES} from './invitation';
import {api,session} from './client';
type View='home'|'join'|'chat'|'host';

const rooms=[['weekend','The weekend table'],['food','Food & tiny obsessions'],['games','Just one more game']];
const RULES=[['18+ and here to socialise','Momo is for adults meeting over food, games and conversation. Being friendly doesn’t mean anyone owes you attention, photos or contact details.'],['Kind is the minimum','No harassment, hate, threats, spam or unwanted advances. Respect a no, a quiet moment, and someone leaving early.'],['Private means private','Don’t share someone’s phone number, messages, real name or photo without their permission. Use a nickname, but don’t pretend to be someone else.'],['A plan you can see upfront','A host confirms the date, public venue, group plan and full cost before you commit. A wish or an invite request is not a booking. This site doesn’t collect payments.'],['Meet in public places','Use the confirmed venue, never someone’s home. Arrange your own travel and tell someone you trust where you’ll be. Tell the venue about allergies directly.'],['If something feels wrong','Use the flag next to a chat message to report it, or hide that member’s messages. Hosts review reports. This is not an emergency service.']];

export default function Momo({view='home'}:{view?:View}){
const{theme}=useBrand();const names=themeNames(theme);
const[data,setData]=useState<any>({events:[],gallery:[],wishes:[]}),[me,setMe]=useState<any>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[room,setRoom]=useState('weekend'),[messages,setMessages]=useState<any[]>([]),[text,setText]=useState(''),[avatar,setAvatar]=useState(0),[host,setHost]=useState<any>(null),[report,setReport]=useState<any>(null),[deleteConfirm,setDeleteConfirm]=useState(false),[letter,setLetter]=useState('hero'),[eventParam,setEventParam]=useState('');
async function refreshMe(){const r=await fetch('/api/community?view=me'),d:any=await r.json();setMe(d);if(d.profile)setAvatar(d.profile.avatar);if(d.invite?.letterStyle)setLetter(d.invite.letterStyle)}
async function load(){const r=await fetch('/api/community'),d:any=await r.json();if(!r.ok)throw Error(d.error);setData(d)}
async function loadChat(){const r=await fetch('/api/community?view=chat&room='+room),d:any=await r.json();if(r.ok)setMessages(d.messages);else if(r.status!==401)setError(d.error)}
async function loadHost(){const r=await fetch('/api/community?view=host'),d:any=await r.json();setHost(d)}
useEffect(()=>{const q=new URLSearchParams(location.search);setEventParam(q.get('event')||'');const r=q.get('room');if(r&&/^(weekend|food|games|w_[0-9a-f-]{36})$/.test(r))setRoom(r)},[]);
useEffect(()=>{load().catch(e=>setError(e.message));refreshMe().catch(()=>setMe({signedIn:false}));if(view==='host')loadHost();},[view]);
useEffect(()=>{if(me&&location.hash)document.getElementById(location.hash.slice(1))?.scrollIntoView()},[!!me,me?.signedIn]);
useEffect(()=>{if(view==='chat'&&me?.signedIn){loadChat();const timer=setInterval(()=>{if(!document.hidden)loadChat()},5000);return()=>clearInterval(timer)}},[room,view,me?.signedIn]);
useEffect(()=>{if(!report&&!deleteConfirm)return;const previous=document.activeElement as HTMLElement;const close=()=>{setReport(null);setDeleteConfirm(false)};const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')close()};document.addEventListener('keydown',handler);const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',handler);document.body.style.overflow=old;previous?.focus()}},[report,deleteConfirm]);
async function run(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Please try again.')}finally{setBusy(false)}}
async function submitInvite(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(async()=>{await api('invite',{phone:f.get('phone'),city:f.get('city'),letterStyle:f.get('letterStyle'),consent:f.get('consent')==='on',adult:f.get('adult')==='on',eventId:new URLSearchParams(location.search).get('event'),foodTheme:theme});setNotice('You’re on the list. The host sees your note and shares the full plan before anything is confirmed.');await refreshMe()})}
async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;await run(async()=>{const r=await fetch('/api/upload',{method:'POST',body:new FormData(form)}),d:any=await r.json();if(!r.ok)throw Error(d.error);setNotice('Photo saved.');form.reset();await load();await refreshMe()})}
const returnTo=view==='home'?'/':'/'+view;
const signIn=!me?<p className="hint">Opening…</p>:me.auth==='device'?<div className="signin"><Armchair size={26}/><h3>Pull up a chair.</h3><p>No email, no password. Your seat is saved on this device, so pick a nickname and you’re in. Nobody sees anything except your nickname.</p><button className="button blue" disabled={busy} onClick={()=>run(async()=>{await session('start');await refreshMe();setNotice('Your chair is ready. Pick a nickname next.')})}>Pull up a chair</button></div>:<div className="signin"><Lock size={23}/><h3>A nickname outside.<br/>A secure sign-in inside.</h3><p>Sign in to save your spot or join the conversation. Other members won’t see your email or phone number.</p><a className="button blue" target="_top" href={'/signin-with-chatgpt?return_to='+encodeURIComponent(returnTo)}>Continue with ChatGPT</a></div>;
const previewBanner=me?.storage==='preview'&&<div className="preview-banner">Preview mode: this deployment doesn’t keep data permanently yet, so chats and wishes may reset.</div>;
const profileForm=me?.signedIn&&<form className="profile-form" id="profile" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{await api('profile',{nickname:f.get('nickname'),avatar,adult:f.get('adult')==='on',rules:f.get('rules')==='on'});await refreshMe();setNotice('Saved. That’s your name at the table.')})}}><label>Nickname<input name="nickname" required minLength={2} maxLength={30} defaultValue={me.profile?.nickname||''} placeholder="e.g. Saturday Club"/></label><span className="label">Your food face</span><div className="avatar-options">{names.map((x,i)=><button key={x} type="button" aria-label={x} aria-pressed={avatar===i} className={avatar===i?'chosen':''} onClick={()=>setAvatar(i)}><Avatar i={i}/><small>{x}</small></button>)}</div><label className="check"><input name="adult" type="checkbox" required defaultChecked={!!me.profile}/>I’m 18 or older.</label><label className="check"><input name="rules" type="checkbox" required defaultChecked={!!me.profile}/>I agree to the <a href="/join#rules">table rules</a> and <a href="/join#privacy">privacy notice</a>.</label><button className="button blue" disabled={busy}>{me.profile?'Update my nickname':'Save my nickname'}</button></form>;
const nextEvent=data.events.find((e:any)=>Date.parse(e.date)>Date.now()-6*3600000);

return <>
<header className="topbar"><a className="logo" href="/" aria-label="Momo home">{wordmark(theme)}<span>✳</span></a>
<nav className="tabs" aria-label="Main"><a className={view==='home'?'on':''} href="/" aria-current={view==='home'?'page':undefined}><Home size={19}/><span>Ghar</span></a><a className={view==='chat'?'on':''} href="/chat" aria-current={view==='chat'?'page':undefined}><MessageCircle size={19}/><span>Adda</span></a></nav>
<div className="topright">{me?.admin&&<a className="host-link" href="/host">Host</a>}<a className={'button small '+(view==='join'?'':'blue')} href="/join">{me?.invite?'My spot':'Count me in'}</a></div></header>

{view==='home'&&<PlayfulHome data={data} me={me} busy={busy} run={run} reload={load} signIn={signIn} onError={setError}/>}

{view==='chat'&&<main className="page adda">{previewBanner}<div className="page-head"><div><span className="handwritten">the adda.</span><h1 className="page-title">Say a little <em>hello.</em></h1><p>The group chat that actually meets. A nickname is plenty. Be kind, be curious, be yourself.</p></div><ThemeSwitch/></div>
<div className="room-pills" role="tablist" aria-label="Chat rooms">{rooms.map(([id,name])=><button key={id} role="tab" aria-selected={room===id} onClick={()=>setRoom(id)} className={room===id?'on':''}>{name}</button>)}{me?.gangs?.map((g:any)=><button key={g.room} role="tab" aria-selected={room===g.room} onClick={()=>setRoom(g.room)} className={'gang-pill '+(room===g.room?'on':'')}>✳ {g.title}</button>)}</div>{me?.signedIn&&!me?.gangs?.length&&<p className="hint">Join a wish on the <a className="hand-link" href="/#wishes">wish wall</a> and its gang gets a private room here.</p>}
<section className="chat-box"><div className="chat-heading"><h3>{rooms.find(x=>x[0]===room)?.[1]||me?.gangs?.find((g:any)=>g.room===room)?.title||'Gang room'}</h3>{room.startsWith('w_')&&<span className="pill">only this gang can see this</span>}<span className="pill">18+ · <a href="/join#rules">table rules</a></span></div>{!me?.signedIn?<div className="chat-gate">{signIn}</div>:<><div className="messages" aria-live="polite">{!messages.length&&<div className="empty-chat"><Avatar i={2} large/><h3>Every good table starts with a hello.</h3><p>No messages here yet. Tell us your go-to comfort food.</p></div>}{messages.map(m=><div className={'message '+(m.mine?'mine':'')} key={m.id}><Avatar i={m.avatar} photo={m.photo}/><div><strong>{m.nickname}</strong><time>{new Date(m.created).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</time><p>{m.body}</p></div>{!m.mine&&<button className="icon-button" aria-label={'Report message by '+m.nickname} onClick={()=>setReport(m)}><Flag size={15}/></button>}</div>)}</div>
{me.profile?<form className="composer" onSubmit={e=>{e.preventDefault();run(async()=>{await api('message',{room,body:text});setText('');await loadChat()})}}><input aria-label="Message" placeholder="What’s on your mind?" value={text} maxLength={500} onChange={e=>setText(e.target.value)}/><button className="button blue" aria-label="Send message" disabled={busy||!text.trim()}><Send size={18}/></button></form>:<div className="composer-setup"><h3>First, a name for the table.</h3><p>You don’t have to use your real name.</p>{profileForm}</div>}</>}</section>
<p className="future-note"><Lock size={15}/> One-to-one chats after you’ve met at a meetup are planned for later.</p></main>}

{view==='join'&&<main className="page join">{previewBanner}
<section className="join-hero"><div><span className="handwritten">count me in.</span><h1 className="page-title">Come and <em>be found.</em></h1><p>Leave your WhatsApp number for weekend invites. You’ll get the date, a public venue and the full cost before you decide. No pressure to come, and you can leave the list anytime.</p><ThemeSwitch/></div><Cast className="join-cast"/></section>
<div className="join-grid">
<section className="card" id="spot"><span className="eyebrow">THE INVITE LIST</span><h2>Save my spot.</h2>{(()=>{const ev=data.events.find((e:any)=>e.id===eventParam);return ev?<div className="seat-for"><span className="eyebrow">ASKING FOR A SEAT AT</span><b>{ev.title}</b><small>{new Date(ev.date).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Kolkata'})} IST · {ev.venue} · {ev.cost}</small></div>:null})()}{!me?.signedIn?signIn:<form onSubmit={submitInvite}><label>WhatsApp number<input name="phone" type="tel" autoComplete="tel" placeholder="+91 98765 43210" required maxLength={20}/></label><label>Your city<input name="city" placeholder="Where should we meet?" required minLength={2} maxLength={60} defaultValue={me?.invite?.city||'Ahmedabad'}/></label><fieldset className="letter-choice"><legend>Which postcard should your invite look like?</legend>{LETTER_STYLES.map(s=><label key={s.id} className={'letter-radio ls-'+s.id}><input type="radio" name="letterStyle" value={s.id} checked={letter===s.id} onChange={()=>setLetter(s.id)}/><b>{s.name}</b><small>{s.note}</small></label>)}</fieldset><label className="check"><input type="checkbox" name="adult" required/>I’m 18 or older.</label><label className="check"><input type="checkbox" name="consent" required/>I agree to receive Momo weekend invites on WhatsApp and have read the <a href="#privacy">privacy notice</a>. I can opt out anytime.</label><button className="button blue full" disabled={busy}>{busy?'Saving…':me?.invite?'Update my spot':'Save my spot'}</button><p className="hint">Saving your spot doesn’t send a message or book anything. A host reviews it first.</p></form>}
{me?.invite&&<div className="request-receipt"><span className="eyebrow">YOUR NOTE REACHED THE HOST</span><h3>{me.invite.reference}</h3><dl><div><dt>City</dt><dd>{me.invite.city}</dd></div><div><dt>Number</dt><dd>{me.invite.maskedPhone}</dd></div><div><dt>Plan</dt><dd>{me.invite.eventTitle||'First meetup interest list'}</dd></div><div><dt>Postcard</dt><dd>{LETTER_STYLES.find(s=>s.id===me.invite.letterStyle)?.name}</dd></div><div><dt>Status</dt><dd>{me.invite.status}</dd></div><div><dt>WhatsApp</dt><dd>{me.invite.deliveryStatus||'Not sent'}</dd></div></dl><button className="textbutton" disabled={busy} onClick={()=>run(async()=>{await api('withdraw');await refreshMe();setNotice('You’ve left the invite list. Your phone number was removed.')})}>Leave the list</button></div>}</section>
<section className="card"><span className="eyebrow">YOUR NAME AT THE TABLE</span><h2>Pick a nickname.</h2>{!me?.signedIn?<p className="hint">Pull up a chair first (left).</p>:profileForm}</section>
</div>
<section className="card wide"><span className="eyebrow">YOUR POSTCARD</span><h2>See how your invite will look.</h2><Letters key={letter} initial={letter as any} event={nextEvent} onError={setError}/></section>
<section className="card wide"><span className="eyebrow">THIS IS WHO’S COMING ON SATURDAY</span><h2>Make your member badge.</h2><BadgeMaker nickname={me?.profile?.nickname} avatar={avatar} onError={setError}/></section>
<section className="fine-print" id="rules"><h2>The table rules</h2><div className="rules">{RULES.map(([h,p])=><details key={h}><summary>{h}</summary><p>{p}</p></details>)}</div></section>
<section className="fine-print" id="privacy"><h2>Your privacy, in plain words</h2>
<details open><summary>What we save, and why</summary><p>{me?.auth==='device'?'Your seat is a random code saved in a cookie on this device. We don’t ask for your email.':'We use your sign-in identity to secure your account.'} Your nickname, food avatar and messages are visible to signed-in members. Your WhatsApp number, city, postcard choice, consent version and request time are stored so hosts can arrange invitations. Hosts can connect activity to your account. This is a pseudonymous community, not a promise of complete anonymity.</p></details>
<details><summary>Your number stays off the table</summary><p>Your number never appears in profiles, wishes or chat. Opting in lets hosts send Momo invitations. It doesn’t add you to any WhatsApp group. Automated WhatsApp sending stays off until the business connection and phone verification are set up.</p></details>
<details><summary>Photos & conversations</summary><p>Hosts publish meetup photos only with permission from people in them. Badge photos are drawn on your device and never uploaded. Chat is not end-to-end encrypted; hosts can review reports and remove messages.</p></details>
<details><summary>Your choices</summary><p>Leave the invite list to remove your phone number. Delete your Momo data to remove your profile, wishes, invite request, messages and reports. Copies already received by other people can’t be recalled. Contact: the.world.is.waiting.for.uu@gmail.com. This preview notice is not a legal certification.</p></details>
{me?.signedIn&&<div className="actions"><button className="button" onClick={()=>run(async()=>{await api('withdraw');await refreshMe();setNotice('Invite request and phone number removed.')})}>Leave invite list</button><button className="button" onClick={()=>setDeleteConfirm(true)}>Delete my Momo data</button>{me.auth==='device'&&<button className="textbutton" onClick={()=>run(async()=>{await session('signout');await refreshMe();setNotice('You left this device’s seat.')})}><LogOut size={16}/>Leave this seat</button>}</div>}
</section></main>}

{view==='host'&&(host?.error&&me?.auth==='device'?<main className="page"><section className="card narrow"><ShieldCheck/><h2>Host corner</h2><p>Enter the host passcode set in the deployment settings.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{await session('host',{passcode:f.get('passcode')});await refreshMe();await loadHost()})}}><label>Passcode<input name="passcode" type="password" autoComplete="current-password" required/></label><button className="button blue" disabled={busy}><KeyRound size={17}/>Open the host notebook</button></form></section></main>:<HostDesk data={data} host={host} busy={busy} run={run} api={api} load={load} loadHost={loadHost} upload={upload} notify={setNotice}/>)}

{(error||notice)&&<div className={'toast '+(error?'error':'')} role={error?'alert':'status'}><span>{error||notice}</span><button aria-label="Dismiss notification" onClick={()=>{setError('');setNotice('')}}><X size={18}/></button></div>}
<footer><div className="foot-brand"><a className="logo" href="/">{wordmark(theme)}<span>✳</span></a><p>Make a wish. We’ll get your gang ready.</p></div><div className="foot-food" aria-hidden="true">{themeKinds(theme).map(k=><FoodIcon key={k} kind={k}/>)}</div><div className="footer-links"><a href="/join#rules">Table rules</a><a href="/join#privacy">Privacy</a><a href="mailto:the.world.is.waiting.for.uu@gmail.com">Say hi</a></div><small>Made for friends we haven’t met yet · 18+</small></footer>
{report&&<div className="overlay" role="dialog" aria-modal="true" aria-label="Report a message"><form className="modal" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{await api('report',{messageId:report.id,reason:f.get('reason')});setReport(null);setNotice('Report saved for the hosts to review.')})}}><button type="button" className="modal-close" aria-label="Close report" onClick={()=>setReport(null)}><X/></button><h2>Keep the table kind.</h2><label>What happened?<textarea name="reason" required minLength={3} maxLength={300} autoFocus/></label><button className="button blue" disabled={busy}>Send report</button><button type="button" className="textbutton" onClick={()=>run(async()=>{await api('block',{messageId:report.id});setReport(null);await loadChat();setNotice('This member’s messages are now hidden from you.')})}>Hide this member’s messages</button></form></div>}
{deleteConfirm&&<div className="overlay" role="dialog" aria-modal="true" aria-label="Delete Momo data"><div className="modal"><h2>Leave no crumbs?</h2><p>This permanently deletes your Momo profile, wishes, messages and invite request.</p><div className="actions"><button autoFocus className="button" onClick={()=>setDeleteConfirm(false)}>Keep my data</button><button className="button blue" disabled={busy} onClick={()=>run(async()=>{await api('deleteAccount');if(me?.auth==='device')await session('signout').catch(()=>{});await refreshMe();await load();setDeleteConfirm(false);setNotice('Your Momo data has been deleted.')})}>Delete my data</button></div></div></div>}
</>}
