export function escapeHtml(value:unknown){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))}
export function letterShell(title:string,body:string,footer:string,style='notebook',theme='momo'){
 const color=style==='princess'?'#8a3b65':style==='hero'?'#b14525':'#295990';
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)}</title></head><body style="margin:0;background:#f2ebdc;color:#342e29;font-family:Georgia,serif;line-height:1.7"><table role="presentation" style="width:100%;border-collapse:collapse"><tr><td style="padding:24px 12px"><table role="presentation" style="width:100%;max-width:580px;margin:auto;background:#fffaf0;border:2px dashed ${color};border-radius:12px"><tr><td style="padding:28px"><p style="color:${color};font-family:Arial,sans-serif;font-size:12px;letter-spacing:2px">MOMO · A LITTLE LETTER · ${theme==='menu'?'THE WHOLE MENU':'DIFFERENT FILLINGS, SAME TABLE'}</p><h1 style="font-size:28px;color:${color};line-height:1.3">${escapeHtml(title)}</h1>${body}<p style="margin-top:28px">Kal milte hain?<br>— Momo ✳</p><hr style="border:0;border-top:1px dashed #b9aa91"><div style="font-family:Arial,sans-serif;font-size:12px;color:#554c43">${footer}</div></td></tr></table></td></tr></table></body></html>`;
}
export function invitationLetter(event:InvitationEvent,invite:Pick<EmailInviteRow,'nickname'|'letter_style'|'food_theme'>,joinUrl:string,unsubscribeUrl:string){
 const date=new Date(event.date).toLocaleString('en-IN',{dateStyle:'full',timeStyle:'short',timeZone:'Asia/Kolkata'})+' IST';
 const greeting=`Hey ${invite.nickname||'there'},`;
 const body=`<p>${escapeHtml(greeting)}</p><p>There’s a place for you at the table, if this weekend feels right.</p><h2>${escapeHtml(event.title)}</h2><p><b>When:</b> ${escapeHtml(date)}<br><b>Where:</b> ${escapeHtml(event.venue)}<br><b>Full cost:</b> ${escapeHtml(event.cost)}</p><p style="white-space:pre-wrap">${escapeHtml(event.description)}</p><p><a href="${escapeHtml(joinUrl)}" style="color:#295990">Read the plan on Momo →</a></p><p>This letter is an invitation, not a confirmed booking. Contact the host listed in the plan to confirm a seat. No pressure to come.</p>`;
 const footer=`You asked for Momo weekend letters. <a href="${escapeHtml(unsubscribeUrl)}" style="color:#295990">Leave the email list</a>. Your address stays out of member profiles and chat.`;
 return {subject:`A little Momo letter: ${String(event.title).replace(/[\r\n]/g,' ')}`,html:letterShell('Come along?',body,footer,invite.letter_style,invite.food_theme),text:`${greeting}\n\nCome along?\n${event.title}\nWhen: ${date}\nWhere: ${event.venue}\nFull cost: ${event.cost}\n\n${event.description}\n\nRead the plan: ${joinUrl}\nThis is an invitation, not a confirmed booking. Contact the host listed in the plan to confirm a seat. No pressure to come.\n\n— Momo\nLeave the email list: ${unsubscribeUrl}`};
}
import type {InvitationEvent,EmailInviteRow} from './invitation-types';
