import {env} from 'cloudflare:workers';
import {db} from './momo-server';
import {memberIsActive} from './member-access';
import {escapeHtml,letterShell,invitationLetter} from './email-letter';
import {deliverEmail} from './email-provider';
import type {EmailInviteInput,EmailInviteRow,InvitationEvent} from './invitation-types';
const CONSENT='email-weekend-letters-v1:2026-10-09';
const DAY=86400000;
export function emailAddress(value:unknown){if(typeof value!=='string')throw Error('Please enter your email address.');const email=value.trim().toLowerCase();if(email.length>254||! /^[a-z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-z0-9](?:[a-z0-9-]*[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)+$/.test(email))throw Error('Please enter a valid email address.');return email}
export function emailConfig(){const e=env as unknown as Record<string,string>,provider=e.EMAIL_PROVIDER||'gmail';const required=provider==='gmail'?['GMAIL_CLIENT_ID','GMAIL_CLIENT_SECRET','GMAIL_REFRESH_TOKEN','GMAIL_SENDER','EMAIL_PUBLIC_URL']:['RESEND_API_KEY','EMAIL_FROM','EMAIL_PUBLIC_URL'];const missing=required.filter(k=>!e[k]);if(!['gmail','resend'].includes(provider))missing.push('EMAIL_PROVIDER');if(e.EMAIL_SENDING_ENABLED!=='true')missing.push('EMAIL_SENDING_ENABLED');let url:URL|null=null;try{url=new URL(e.EMAIL_PUBLIC_URL);if(url.protocol!=='https:'||url.username||url.password||url.search||url.hash||url.pathname!=='/')url=null}catch{}if(!url&&!missing.includes('EMAIL_PUBLIC_URL'))missing.push('EMAIL_PUBLIC_URL');if(provider==='gmail'&&e.GMAIL_SENDER){try{emailAddress(e.GMAIL_SENDER)}catch{missing.push('GMAIL_SENDER')}}if(provider==='resend'&&e.EMAIL_FROM&&/[\r\n]/.test(e.EMAIL_FROM))missing.push('EMAIL_FROM');return {configured:missing.length===0,missing,mode:provider==='gmail'?'Gmail API':'Resend',automaticSignupMessages:false}}
function publicUrl(){if(!emailConfig().configured)throw Error('Please wait for the email sender to be connected. Your request is saved.');return new URL((env as unknown as Record<string,string>).EMAIL_PUBLIC_URL).origin}
export async function tokenHash(value:string){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,'0')).join('')}
function token(){return Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('')}
export function maskEmail(email:string){const [name,domain]=email.split('@');return name[0]+'•••@'+domain}
async function reserveBudget(key:string,limit:number,cooldown=0){const now=Date.now();const result=await db().prepare('INSERT INTO email_budgets(id,count,last) VALUES(?,1,?) ON CONFLICT(id) DO UPDATE SET count=count+1,last=excluded.last WHERE count<? AND last<=?').bind(key,now,limit,now-cooldown).run();if(!result.meta.changes)throw Error('Please wait before sending another letter. The email limit for this pilot may have been reached.')}
async function mail(to:string,letter:{subject:string,html:string,text:string},key:string){
 publicUrl();return deliverEmail(to,letter,key,(env as unknown as Record<string,string>).EMAIL_PROVIDER||'gmail');
}
export async function saveEmailInvite(userId:string,b:EmailInviteInput){
 const email=emailAddress(b.email);if(b.consent!==true||b.adult!==true)throw Error('Please confirm you are 18+ and agree to email invitations.');if(typeof b.city!=='string'||b.city.trim().length<2||b.city.trim().length>60)throw Error('Please enter your city.');
 const eventId=typeof b.eventId==='string'&&b.eventId?b.eventId:null;if(eventId&&!await db().prepare('SELECT id FROM events WHERE id=?').bind(eventId).first())throw Error('Please choose an available plan.');const now=Date.now();
 await db().prepare("INSERT INTO email_invites(user_id,email,city,event_id,consent,status,food_theme,letter_style,revision,created,updated) VALUES(?,?,?,?,?,'requested',?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET email=excluded.email,city=excluded.city,event_id=excluded.event_id,consent=excluded.consent,status='requested',food_theme=excluded.food_theme,letter_style=excluded.letter_style,updated=excluded.updated,verified_at=CASE WHEN email_invites.email=excluded.email THEN email_invites.verified_at ELSE NULL END,verify_hash=CASE WHEN email_invites.email=excluded.email THEN email_invites.verify_hash ELSE NULL END,verify_expires=CASE WHEN email_invites.email=excluded.email THEN email_invites.verify_expires ELSE NULL END,revision=CASE WHEN email_invites.email=excluded.email THEN email_invites.revision ELSE excluded.revision END").bind(userId,email,b.city.trim(),eventId,CONSENT,b.foodTheme==='menu'?'menu':'momo',typeof b.letterStyle==='string'&&['hero','princess','notebook'].includes(b.letterStyle)?b.letterStyle:'notebook',crypto.randomUUID(),now,now).run();return {ok:true};
}
export async function requestEmailVerification(userId:string){
 const base=publicUrl();const invite=await db().prepare('SELECT * FROM email_invites WHERE user_id=?').bind(userId).first<EmailInviteRow>();if(!invite?.consent)throw Error('Please save your email request first.');if(invite.verified_at)return {ok:true,verified:true};const now=Date.now(),day=Math.floor(now/DAY);
 await reserveBudget('verify:'+day+':'+await tokenHash(invite.email),3,60000);await reserveBudget('all:'+day,20);await db().prepare('DELETE FROM email_budgets WHERE last<?').bind(now-2*DAY).run();
 const code=token(),hash=await tokenHash(code);const result=await db().prepare('UPDATE email_invites SET verify_hash=?,verify_expires=? WHERE user_id=? AND email=? AND revision=? AND consent=? AND verified_at IS NULL').bind(hash,now+30*60000,userId,invite.email,invite.revision,CONSENT).run();if(!result.meta.changes)throw Error('Please save your current email request again.');
 // Fragment tokens stay out of HTTP URLs, server logs and referrers. GET never verifies.
 const link=base+'/join#email-confirm='+code;const text=`You asked for Momo weekend letters. Confirm your email: ${link}\nThis link expires in 30 minutes. If this was not you, ignore this letter; no invitations will be sent.\n— Momo`;
 const html=letterShell('A letter for you?',`<p>You asked for Momo weekend letters.</p><p><a href="${escapeHtml(link)}" style="color:#295990">Confirm my email →</a></p><p>This link expires in 30 minutes. Opening it alone does not confirm your address.</p>`,'If this was not you, ignore this letter. No invitations will be sent.',invite.letter_style,invite.food_theme);
 try{await mail(invite.email,{subject:'Confirm your Momo letters',html,text},'verify/'+hash)}catch(error){await db().prepare('UPDATE email_invites SET verify_hash=NULL,verify_expires=NULL WHERE user_id=? AND verify_hash=?').bind(userId,hash).run();throw error}return {ok:true,status:'accepted'};
}
export async function emailTokenAction(kind:string,code:unknown){
 if(typeof code!=='string'||!/^[a-f0-9]{64}$/.test(code))throw Error('Please open a valid link from your Momo letter.');const hash=await tokenHash(code),now=Date.now();
 if(kind==='confirm'){
  const changed=await db().prepare('UPDATE email_invites SET verified_at=?,verify_hash=NULL,verify_expires=NULL WHERE verify_hash=? AND verify_expires>? AND consent=?').bind(now,hash,now,CONSENT).run();if(!changed.meta.changes)throw Error('Please request a new confirmation letter. This link has expired or already been used.');return {ok:true};
 }
 if(kind==='unsubscribe'){
  // Match the original consent revision: a forwarded or old link cannot cancel a later signup.
  await db().batch([db().prepare("UPDATE email_deliveries SET status='withdrawn',updated=? WHERE user_id IN (SELECT i.user_id FROM email_invites i JOIN email_deliveries d ON d.user_id=i.user_id AND d.revision=i.revision WHERE d.unsubscribe_hash=?)").bind(now,hash),db().prepare('DELETE FROM email_invites WHERE EXISTS(SELECT 1 FROM email_deliveries d WHERE d.user_id=email_invites.user_id AND d.revision=email_invites.revision AND d.unsubscribe_hash=?)').bind(hash),db().prepare('UPDATE email_deliveries SET unsubscribe_hash=NULL WHERE unsubscribe_hash=?').bind(hash)]);
  return {ok:true};
 }
 throw Error('Please choose a valid email action.');
}
async function emailPlan(eventId:string){const event=await db().prepare('SELECT * FROM events WHERE id=?').bind(eventId).first<InvitationEvent>();if(!event||!Number.isFinite(Date.parse(event.date))||Date.parse(event.date)<=Date.now())throw Error('Please choose an upcoming published plan.');return event}
export async function previewEmailLetter(userId:string,eventId:string){const event=await emailPlan(eventId);const invite=await db().prepare('SELECT i.*,p.nickname FROM email_invites i LEFT JOIN profiles p ON p.id=i.user_id WHERE i.user_id=?').bind(userId).first<EmailInviteRow>();if(!invite)throw Error('Please choose an email request.');const base=emailConfig().configured?new URL((env as unknown as Record<string,string>).EMAIL_PUBLIC_URL).origin:'https://momo.example';return {eventId,userId,...invitationLetter(event,invite,base+'/join?event='+encodeURIComponent(eventId),base+'/join#email-unsubscribe=preview'),preview:true}}
export async function sendEmailInvitation(userId:string,eventId:string){
 if(!await memberIsActive(userId))throw Error('This member is suspended; no invitation can be sent.');
 const base=publicUrl(),event=await emailPlan(eventId);const invite=await db().prepare('SELECT i.*,p.nickname FROM email_invites i LEFT JOIN profiles p ON p.id=i.user_id WHERE i.user_id=?').bind(userId).first<EmailInviteRow>();if(!invite?.verified_at||invite.consent!==CONSENT||!['reviewed','confirmed','invited'].includes(invite.status))throw Error('Please review this request and confirm email ownership first.');if(invite.event_id&&invite.event_id!==eventId)throw Error('Please choose the plan this person requested.');
 const id=await tokenHash(invite.email+':'+eventId),now=Date.now(),code=token();const inserted=await db().prepare("INSERT OR IGNORE INTO email_deliveries(id,user_id,event_id,revision,unsubscribe_hash,status,created,updated) VALUES(?,?,?,?,?,'sending',?,?)").bind(id,userId,eventId,invite.revision,await tokenHash(code),now,now).run();if(!inserted.meta.changes)throw Error('Please check the existing email attempt. This inbox already has an attempt for this plan.');
 try{
  await reserveBudget('all:'+Math.floor(now/DAY),20);
  const current=await db().prepare("SELECT user_id FROM email_invites WHERE user_id=? AND email=? AND revision=? AND consent=? AND verified_at IS NOT NULL AND status IN ('reviewed','confirmed','invited') AND (event_id IS NULL OR event_id=?) AND NOT EXISTS(SELECT 1 FROM member_controls mc WHERE mc.user_id=email_invites.user_id AND mc.status='suspended')").bind(userId,invite.email,invite.revision,CONSENT,eventId).first();if(!current)throw Error('Please review the current request; the email list changed.');
  const letter=invitationLetter(event,invite,base+'/join?event='+encodeURIComponent(eventId),base+'/join#email-unsubscribe='+code);const messageId=await mail(invite.email,letter,'invite/'+id);
  await db().batch([db().prepare("UPDATE email_deliveries SET message_id=?,status=CASE WHEN status='sending' THEN 'accepted' ELSE status END,updated=? WHERE id=?").bind(messageId,Date.now(),id),db().prepare("UPDATE email_invites SET status='invited' WHERE user_id=? AND revision=? AND status IN ('reviewed','confirmed','invited') AND EXISTS(SELECT 1 FROM email_deliveries WHERE id=? AND status='accepted')").bind(userId,invite.revision,id)]);return {ok:true,status:'accepted'};
 }catch(error){const message=error instanceof Error?error.message:'Email outcome unknown.';await db().prepare("UPDATE email_deliveries SET status=?,error=?,updated=? WHERE id=? AND status='sending'").bind(message.includes('unknown')?'unknown':'failed',message,Date.now(),id).run();throw error}
}
