// Generated by scripts/embed-migrations.mjs. Do not edit by hand.
export const migrations:{name:string;sql:string}[]=[
 {
  "name": "0000_wide_starfox",
  "sql": "CREATE TABLE `blocks` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`blocked_id` text NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `idx_blocks_user` ON `blocks` (`user_id`);--> statement-breakpoint\nCREATE TABLE `events` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`title` text NOT NULL,\n\t`date` text NOT NULL,\n\t`venue` text NOT NULL,\n\t`cost` text NOT NULL,\n\t`description` text NOT NULL,\n\t`category` text NOT NULL,\n\t`created` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE TABLE `gallery` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`caption` text NOT NULL,\n\t`category` text NOT NULL,\n\t`created` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE TABLE `invites` (\n\t`user_id` text PRIMARY KEY NOT NULL,\n\t`phone` text NOT NULL,\n\t`city` text NOT NULL,\n\t`event_id` text,\n\t`consent` text NOT NULL,\n\t`status` text DEFAULT 'requested' NOT NULL,\n\t`created` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE TABLE `messages` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`room` text NOT NULL,\n\t`body` text NOT NULL,\n\t`created` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `idx_messages_room_created` ON `messages` (`room`,`created`);--> statement-breakpoint\nCREATE TABLE `profiles` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`nickname` text NOT NULL,\n\t`avatar` integer DEFAULT 0 NOT NULL,\n\t`photo` text,\n\t`last_message` integer DEFAULT 0 NOT NULL,\n\t`created` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE TABLE `reports` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`message_id` text NOT NULL,\n\t`reason` text NOT NULL,\n\t`created` integer NOT NULL\n);\n"
 },
 {
  "name": "0001_yummy_silvermane",
  "sql": "CREATE TABLE `deliveries` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`event_id` text NOT NULL,\n\t`message_id` text,\n\t`status` text NOT NULL,\n\t`error` text,\n\t`created` integer NOT NULL,\n\t`updated` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `idx_deliveries_message` ON `deliveries` (`message_id`);--> statement-breakpoint\nCREATE INDEX `idx_deliveries_user_created` ON `deliveries` (`user_id`,`created`);--> statement-breakpoint\nALTER TABLE `invites` ADD `food_theme` text DEFAULT 'momo' NOT NULL;"
 },
 {
  "name": "0002_wishes_and_sessions",
  "sql": "CREATE TABLE `sessions` (\n\t`token_hash` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`host` integer DEFAULT 0 NOT NULL,\n\t`created` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `idx_sessions_user` ON `sessions` (`user_id`);--> statement-breakpoint\nCREATE TABLE `wish_joins` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`wish_id` text NOT NULL,\n\t`user_id` text NOT NULL,\n\t`created` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `idx_wish_joins_wish` ON `wish_joins` (`wish_id`);--> statement-breakpoint\nCREATE INDEX `idx_wish_joins_user` ON `wish_joins` (`user_id`);--> statement-breakpoint\nCREATE TABLE `wishes` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`title` text NOT NULL,\n\t`when_text` text NOT NULL,\n\t`area` text NOT NULL,\n\t`spots` integer NOT NULL,\n\t`status` text DEFAULT 'open' NOT NULL,\n\t`created` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `idx_wishes_created` ON `wishes` (`created`);--> statement-breakpoint\nCREATE INDEX `idx_wishes_user` ON `wishes` (`user_id`);--> statement-breakpoint\nALTER TABLE `invites` ADD `letter_style` text DEFAULT 'notebook' NOT NULL;"
 },
 {
  "name": "0003_events_wish_link",
  "sql": "ALTER TABLE `events` ADD `wish_id` text;"
 },
 {
  "name": "0004_report_kind",
  "sql": "ALTER TABLE `reports` ADD `kind` text DEFAULT 'message' NOT NULL;"
 },
 {
  "name": "0005_phone_verification",
  "sql": "CREATE TABLE `phone_verifications` (\n\t`user_id` text PRIMARY KEY NOT NULL,\n\t`phone` text NOT NULL,\n\t`code_hash` text,\n\t`expires` integer NOT NULL,\n\t`created` integer NOT NULL,\n\t`verified_at` integer\n);\n--> statement-breakpoint\nCREATE INDEX `idx_phone_verifications_code` ON `phone_verifications` (`code_hash`,`phone`);"
 },
 {
  "name": "0006_email_letters",
  "sql": "CREATE TABLE `email_budgets` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`count` integer NOT NULL,\n\t`last` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE TABLE `email_deliveries` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`event_id` text NOT NULL,\n\t`revision` text NOT NULL,\n\t`unsubscribe_hash` text,\n\t`message_id` text,\n\t`status` text NOT NULL,\n\t`error` text,\n\t`created` integer NOT NULL,\n\t`updated` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `idx_email_deliveries_user` ON `email_deliveries` (`user_id`);--> statement-breakpoint\nCREATE INDEX `idx_email_deliveries_unsubscribe` ON `email_deliveries` (`unsubscribe_hash`);--> statement-breakpoint\nCREATE TABLE `email_invites` (\n\t`user_id` text PRIMARY KEY NOT NULL,\n\t`email` text NOT NULL,\n\t`city` text NOT NULL,\n\t`event_id` text,\n\t`consent` text NOT NULL,\n\t`status` text DEFAULT 'requested' NOT NULL,\n\t`food_theme` text DEFAULT 'momo' NOT NULL,\n\t`letter_style` text DEFAULT 'notebook' NOT NULL,\n\t`revision` text NOT NULL,\n\t`created` integer NOT NULL,\n\t`updated` integer NOT NULL,\n\t`verified_at` integer,\n\t`verify_hash` text,\n\t`verify_expires` integer\n);\n--> statement-breakpoint\nCREATE INDEX `idx_email_invites_verify` ON `email_invites` (`verify_hash`);"
 },
 {
  "name": "0007_nappy_goliath",
  "sql": "CREATE TABLE `admin_audit` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`actor_id` text NOT NULL,\n\t`action` text NOT NULL,\n\t`subject_id` text NOT NULL,\n\t`note` text,\n\t`created` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `idx_admin_audit_created` ON `admin_audit` (`created`);--> statement-breakpoint\nCREATE TABLE `direct_threads` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_a` text NOT NULL,\n\t`user_b` text NOT NULL,\n\t`created` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `idx_direct_a` ON `direct_threads` (`user_a`);--> statement-breakpoint\nCREATE INDEX `idx_direct_b` ON `direct_threads` (`user_b`);--> statement-breakpoint\nCREATE TABLE `event_attendance` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`event_id` text NOT NULL,\n\t`user_id` text NOT NULL,\n\t`confirmed_by` text NOT NULL,\n\t`attended_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `idx_attendance_user` ON `event_attendance` (`user_id`);--> statement-breakpoint\nCREATE INDEX `idx_attendance_event` ON `event_attendance` (`event_id`);--> statement-breakpoint\nCREATE TABLE `member_controls` (\n\t`user_id` text PRIMARY KEY NOT NULL,\n\t`status` text DEFAULT 'active' NOT NULL,\n\t`reason` text,\n\t`updated` integer NOT NULL\n);\n--> statement-breakpoint\nALTER TABLE `profiles` ADD `dm_opt_in` integer DEFAULT 0 NOT NULL;"
 },
 {
  "name": "0008_serious_impossible_man",
  "sql": "CREATE TABLE `chat_send_limits` (\n\t`user_id` text PRIMARY KEY NOT NULL,\n\t`window_start` integer NOT NULL,\n\t`sent` integer NOT NULL,\n\t`last_id` text NOT NULL\n);\n--> statement-breakpoint\nCREATE TABLE `chat_send_receipts` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`body_hash` text NOT NULL,\n\t`created` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `idx_chat_receipts_user` ON `chat_send_receipts` (`user_id`);"
 }
];
