// Generated by scripts/embed-migrations.mjs. Do not edit by hand.
export const migrations:{name:string;sql:string}[]=[
 {
  "name": "0000_wide_starfox",
  "sql": "CREATE TABLE `blocks` (\r\n\t`id` text PRIMARY KEY NOT NULL,\r\n\t`user_id` text NOT NULL,\r\n\t`blocked_id` text NOT NULL\r\n);\r\n--> statement-breakpoint\r\nCREATE INDEX `idx_blocks_user` ON `blocks` (`user_id`);--> statement-breakpoint\r\nCREATE TABLE `events` (\r\n\t`id` text PRIMARY KEY NOT NULL,\r\n\t`title` text NOT NULL,\r\n\t`date` text NOT NULL,\r\n\t`venue` text NOT NULL,\r\n\t`cost` text NOT NULL,\r\n\t`description` text NOT NULL,\r\n\t`category` text NOT NULL,\r\n\t`created` integer NOT NULL\r\n);\r\n--> statement-breakpoint\r\nCREATE TABLE `gallery` (\r\n\t`id` text PRIMARY KEY NOT NULL,\r\n\t`caption` text NOT NULL,\r\n\t`category` text NOT NULL,\r\n\t`created` integer NOT NULL\r\n);\r\n--> statement-breakpoint\r\nCREATE TABLE `invites` (\r\n\t`user_id` text PRIMARY KEY NOT NULL,\r\n\t`phone` text NOT NULL,\r\n\t`city` text NOT NULL,\r\n\t`event_id` text,\r\n\t`consent` text NOT NULL,\r\n\t`status` text DEFAULT 'requested' NOT NULL,\r\n\t`created` integer NOT NULL\r\n);\r\n--> statement-breakpoint\r\nCREATE TABLE `messages` (\r\n\t`id` text PRIMARY KEY NOT NULL,\r\n\t`user_id` text NOT NULL,\r\n\t`room` text NOT NULL,\r\n\t`body` text NOT NULL,\r\n\t`created` integer NOT NULL\r\n);\r\n--> statement-breakpoint\r\nCREATE INDEX `idx_messages_room_created` ON `messages` (`room`,`created`);--> statement-breakpoint\r\nCREATE TABLE `profiles` (\r\n\t`id` text PRIMARY KEY NOT NULL,\r\n\t`nickname` text NOT NULL,\r\n\t`avatar` integer DEFAULT 0 NOT NULL,\r\n\t`photo` text,\r\n\t`last_message` integer DEFAULT 0 NOT NULL,\r\n\t`created` integer NOT NULL\r\n);\r\n--> statement-breakpoint\r\nCREATE TABLE `reports` (\r\n\t`id` text PRIMARY KEY NOT NULL,\r\n\t`user_id` text NOT NULL,\r\n\t`message_id` text NOT NULL,\r\n\t`reason` text NOT NULL,\r\n\t`created` integer NOT NULL\r\n);\r\n"
 },
 {
  "name": "0001_yummy_silvermane",
  "sql": "CREATE TABLE `deliveries` (\r\n\t`id` text PRIMARY KEY NOT NULL,\r\n\t`user_id` text NOT NULL,\r\n\t`event_id` text NOT NULL,\r\n\t`message_id` text,\r\n\t`status` text NOT NULL,\r\n\t`error` text,\r\n\t`created` integer NOT NULL,\r\n\t`updated` integer NOT NULL\r\n);\r\n--> statement-breakpoint\r\nCREATE INDEX `idx_deliveries_message` ON `deliveries` (`message_id`);--> statement-breakpoint\r\nCREATE INDEX `idx_deliveries_user_created` ON `deliveries` (`user_id`,`created`);--> statement-breakpoint\r\nALTER TABLE `invites` ADD `food_theme` text DEFAULT 'momo' NOT NULL;"
 },
 {
  "name": "0002_wishes_and_sessions",
  "sql": "CREATE TABLE `sessions` (\r\n\t`token_hash` text PRIMARY KEY NOT NULL,\r\n\t`user_id` text NOT NULL,\r\n\t`host` integer DEFAULT 0 NOT NULL,\r\n\t`created` integer NOT NULL\r\n);\r\n--> statement-breakpoint\r\nCREATE INDEX `idx_sessions_user` ON `sessions` (`user_id`);--> statement-breakpoint\r\nCREATE TABLE `wish_joins` (\r\n\t`id` text PRIMARY KEY NOT NULL,\r\n\t`wish_id` text NOT NULL,\r\n\t`user_id` text NOT NULL,\r\n\t`created` integer NOT NULL\r\n);\r\n--> statement-breakpoint\r\nCREATE INDEX `idx_wish_joins_wish` ON `wish_joins` (`wish_id`);--> statement-breakpoint\r\nCREATE INDEX `idx_wish_joins_user` ON `wish_joins` (`user_id`);--> statement-breakpoint\r\nCREATE TABLE `wishes` (\r\n\t`id` text PRIMARY KEY NOT NULL,\r\n\t`user_id` text NOT NULL,\r\n\t`title` text NOT NULL,\r\n\t`when_text` text NOT NULL,\r\n\t`area` text NOT NULL,\r\n\t`spots` integer NOT NULL,\r\n\t`status` text DEFAULT 'open' NOT NULL,\r\n\t`created` integer NOT NULL\r\n);\r\n--> statement-breakpoint\r\nCREATE INDEX `idx_wishes_created` ON `wishes` (`created`);--> statement-breakpoint\r\nCREATE INDEX `idx_wishes_user` ON `wishes` (`user_id`);--> statement-breakpoint\r\nALTER TABLE `invites` ADD `letter_style` text DEFAULT 'notebook' NOT NULL;"
 },
 {
  "name": "0003_events_wish_link",
  "sql": "ALTER TABLE `events` ADD `wish_id` text;"
 },
 {
  "name": "0004_report_kind",
  "sql": "ALTER TABLE `reports` ADD `kind` text DEFAULT 'message' NOT NULL;"
 }
];
