import {env} from 'cloudflare:workers';
import {memberIsActive} from './member-access';
import {db} from './momo-server';
import {hasVerifiedPhone,PHONE_VERIFICATION_WINDOW} from './phone-verification';
const required=['WHATSAPP_ACCESS_TOKEN','WHATSAPP_PHONE_NUMBER_ID','WHATSAPP_GRAPH_VERSION','WHATSAPP_TEMPLATE_NAME','WHATSAPP_TEMPLATE_LANGUAGE','WHATSAPP_APP_SECRET','WHATSAPP_VERIFY_TOKEN'];
export function whatsappConfig(){const e=env as any;const missing=required.filter(k=>!e[k]);if(e.WHATSAPP_WEBHOOK_PUBLIC!=='true')missing.push('WHATSAPP_WEBHOOK_PUBLIC');if(e.WHATSAPP_PHONE_VERIFICATION_READY!=='true')missing.push('WHATSAPP_PHONE_VERIFICATION_READY');return {configured:missing.length===0,missing,mode:'Meta Cloud API',automaticSignupMessages:false,webhookPath:'/api/whatsapp/webhook'}}
export function whatsappSettings(){return env as any}
export async function sendInvitation(userId:string,eventId:string){const config=whatsappConfig();if(!config.configured)throw Error('WhatsApp is not connected. Complete the host setup checklist first.');if(!await memberIsActive(userId))throw Error('This member is suspended; no invitation can be sent.');const e=env as any;if(!/^v\d+\.\d+$/.test(e.WHATSAPP_GRAPH_VERSION)||!/^\d+$/.test(e.WHATSAPP_PHONE_NUMBER_ID))throw Error('Check the WhatsApp API version and sender ID.');const invite=await db().prepare('SELECT * FROM invites WHERE user_id=?').bind(userId).first<any>();const event=await db().prepare('SELECT * FROM events WHERE id=?').bind(eventId).first<any>();if(!invite||!invite.consent||!['reviewed','confirmed','invited'].includes(invite.status)||!event)throw Error('The request or event is no longer available.');if(invite.event_id&&invite.event_id!==eventId)throw Error('This request is for a different plan.');if(!await hasVerifiedPhone(userId,invite.phone))throw Error('This phone number must be verified before an automated invitation.');if(!Number.isFinite(Date.parse(event.date))||Date.parse(event.date)<=Date.now())throw Error('Choose an upcoming meetup.');const id=userId+':'+eventId,now=Date.now();const inserted=await db().prepare("INSERT OR IGNORE INTO deliveries(id,user_id,event_id,status,created,updated) VALUES(?,?,?,'sending',?,?)").bind(id,userId,eventId,now,now).run();if(!inserted.meta.changes)throw Error('An invitation attempt already exists for this person and event. Check delivery status before sending again.');const current=await db().prepare("SELECT phone FROM invites i WHERE user_id=? AND phone=? AND consent=? AND status IN ('reviewed','confirmed','invited') AND EXISTS(SELECT 1 FROM phone_verifications v WHERE v.user_id=i.user_id AND v.phone=i.phone AND v.verified_at>=?) AND NOT EXISTS(SELECT 1 FROM member_controls mc WHERE mc.user_id=i.user_id AND mc.status='suspended')").bind(userId,invite.phone,invite.consent,Date.now()-PHONE_VERIFICATION_WINDOW).first();if(!current){await db().prepare("UPDATE deliveries SET status='cancelled',updated=? WHERE id=?").bind(Date.now(),id).run();throw Error('This person has left the invite list.');}
let response:Response;try{response=await fetch(`https://graph.facebook.com/${e.WHATSAPP_GRAPH_VERSION}/${e.WHATSAPP_PHONE_NUMBER_ID}/messages`,{method:'POST',headers:{Authorization:`Bearer ${e.WHATSAPP_ACCESS_TOKEN}`,'Content-Type':'application/json'},signal:AbortSignal.timeout(15000),body:JSON.stringify({messaging_product:'whatsapp',recipient_type:'individual',to:invite.phone.replace(/^\+/,''),type:'template',template:{name:e.WHATSAPP_TEMPLATE_NAME,language:{code:e.WHATSAPP_TEMPLATE_LANGUAGE},components:[{type:'body',parameters:[event.title,new Date(event.date).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})+' IST',event.venue,event.cost].map(text=>({type:'text',text}))}]}})})}catch{await db().prepare("UPDATE deliveries SET status='unknown',error='Network outcome unknown. Do not resend until checked with Meta.',updated=? WHERE id=?").bind(Date.now(),id).run();throw Error('Delivery outcome is unknown. Check Meta before retrying; no automatic retry was made.');}
const result:any=await response.json().catch(()=>({}));const messageId=result.messages?.[0]?.id;if(!response.ok||!messageId){const status=response.ok?'unknown':'failed';const error=response.ok?'Meta did not return a message identifier.':`Meta rejected the request (code ${result.error?.code||response.status}).`;await db().prepare('UPDATE deliveries SET status=?,error=?,updated=? WHERE id=?').bind(status,error,Date.now(),id).run();throw Error(error)}await db().batch([db().prepare("UPDATE deliveries SET message_id=?,status=CASE WHEN status='sending' THEN 'accepted' ELSE status END,updated=? WHERE id=?").bind(messageId,Date.now(),id),db().prepare("UPDATE invites SET status='invited' WHERE user_id=? AND phone=? AND consent=? AND status IN ('reviewed','confirmed','invited') AND EXISTS(SELECT 1 FROM deliveries WHERE id=? AND status NOT IN ('withdrawn','cancelled'))").bind(userId,invite.phone,invite.consent,id)]);return {ok:true,status:'accepted',messageId}}
