import {sqliteTable,text,integer,index} from 'drizzle-orm/sqlite-core';
export const profiles=sqliteTable('profiles',{id:text('id').primaryKey(),nickname:text('nickname').notNull(),avatar:integer('avatar').notNull().default(0),photo:text('photo'),lastMessage:integer('last_message').notNull().default(0),created:integer('created').notNull()});
export const invites=sqliteTable('invites',{userId:text('user_id').primaryKey(),phone:text('phone').notNull(),city:text('city').notNull(),foodTheme:text('food_theme').notNull().default('momo'),eventId:text('event_id'),consent:text('consent').notNull(),status:text('status').notNull().default('requested'),created:integer('created').notNull()});
export const events=sqliteTable('events',{id:text('id').primaryKey(),title:text('title').notNull(),date:text('date').notNull(),venue:text('venue').notNull(),cost:text('cost').notNull(),description:text('description').notNull(),category:text('category').notNull(),created:integer('created').notNull()});
export const messages=sqliteTable('messages',{id:text('id').primaryKey(),userId:text('user_id').notNull(),room:text('room').notNull(),body:text('body').notNull(),created:integer('created').notNull()},t=>[index('idx_messages_room_created').on(t.room,t.created)]);
export const reports=sqliteTable('reports',{id:text('id').primaryKey(),userId:text('user_id').notNull(),messageId:text('message_id').notNull(),reason:text('reason').notNull(),created:integer('created').notNull()});
export const gallery=sqliteTable('gallery',{id:text('id').primaryKey(),caption:text('caption').notNull(),category:text('category').notNull(),created:integer('created').notNull()});
export const blocks=sqliteTable('blocks',{id:text('id').primaryKey(),userId:text('user_id').notNull(),blockedId:text('blocked_id').notNull()},t=>[index('idx_blocks_user').on(t.userId)]);
export const deliveries=sqliteTable('deliveries',{id:text('id').primaryKey(),userId:text('user_id').notNull(),eventId:text('event_id').notNull(),messageId:text('message_id'),status:text('status').notNull(),error:text('error'),created:integer('created').notNull(),updated:integer('updated').notNull()},t=>[index('idx_deliveries_message').on(t.messageId),index('idx_deliveries_user_created').on(t.userId,t.created)]);
