import {sqliteTable,text,integer,index} from 'drizzle-orm/sqlite-core';
export const profiles=sqliteTable('profiles',{id:text('id').primaryKey(),nickname:text('nickname').notNull(),avatar:integer('avatar').notNull().default(0),photo:text('photo'),lastMessage:integer('last_message').notNull().default(0),created:integer('created').notNull()});
export const invites=sqliteTable('invites',{userId:text('user_id').primaryKey(),phone:text('phone').notNull(),city:text('city').notNull(),foodTheme:text('food_theme').notNull().default('momo'),letterStyle:text('letter_style').notNull().default('notebook'),eventId:text('event_id'),consent:text('consent').notNull(),status:text('status').notNull().default('requested'),created:integer('created').notNull()});
export const events=sqliteTable('events',{id:text('id').primaryKey(),title:text('title').notNull(),date:text('date').notNull(),venue:text('venue').notNull(),cost:text('cost').notNull(),description:text('description').notNull(),category:text('category').notNull(),wishId:text('wish_id'),created:integer('created').notNull()});
export const messages=sqliteTable('messages',{id:text('id').primaryKey(),userId:text('user_id').notNull(),room:text('room').notNull(),body:text('body').notNull(),created:integer('created').notNull()},t=>[index('idx_messages_room_created').on(t.room,t.created)]);
// message_id holds the reported message id, or the wish id when kind='wish'.
export const reports=sqliteTable('reports',{id:text('id').primaryKey(),userId:text('user_id').notNull(),messageId:text('message_id').notNull(),kind:text('kind').notNull().default('message'),reason:text('reason').notNull(),created:integer('created').notNull()});
export const gallery=sqliteTable('gallery',{id:text('id').primaryKey(),caption:text('caption').notNull(),category:text('category').notNull(),created:integer('created').notNull()});
export const blocks=sqliteTable('blocks',{id:text('id').primaryKey(),userId:text('user_id').notNull(),blockedId:text('blocked_id').notNull()},t=>[index('idx_blocks_user').on(t.userId)]);
export const deliveries=sqliteTable('deliveries',{id:text('id').primaryKey(),userId:text('user_id').notNull(),eventId:text('event_id').notNull(),messageId:text('message_id'),status:text('status').notNull(),error:text('error'),created:integer('created').notNull(),updated:integer('updated').notNull()},t=>[index('idx_deliveries_message').on(t.messageId),index('idx_deliveries_user_created').on(t.userId,t.created)]);
// "Make a wish": a member proposes a plan and a gang forms around it.
export const wishes=sqliteTable('wishes',{id:text('id').primaryKey(),userId:text('user_id').notNull(),title:text('title').notNull(),whenText:text('when_text').notNull(),area:text('area').notNull(),spots:integer('spots').notNull(),status:text('status').notNull().default('open'),created:integer('created').notNull()},t=>[index('idx_wishes_created').on(t.created),index('idx_wishes_user').on(t.userId)]);
export const wishJoins=sqliteTable('wish_joins',{id:text('id').primaryKey(),wishId:text('wish_id').notNull(),userId:text('user_id').notNull(),created:integer('created').notNull()},t=>[index('idx_wish_joins_wish').on(t.wishId),index('idx_wish_joins_user').on(t.userId)]);
// Device sessions, used only where no trusted sign-in gateway exists (the Vercel deployment).
export const sessions=sqliteTable('sessions',{tokenHash:text('token_hash').primaryKey(),userId:text('user_id').notNull(),host:integer('host').notNull().default(0),created:integer('created').notNull()},t=>[index('idx_sessions_user').on(t.userId)]);
